name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_AWS}}

      - name: Add SSH key passphrase
        run: |
          echo ${{ secrets.SSH_PASSPHRASE }} | ssh-add - > /dev/null
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-129-25-3.us-east-2.compute.amazonaws.com << 'EOF'
            cd /home/ubuntu/apiEcommerce
            git pull origin main
            # Aquí puedes ejecutar cualquier comando necesario para desplegar tu aplicación
            # Ejemplo para un proyecto Node.js
            npm install
            pm2 restart all
          EOF
